### ISSUE TITLE
Interest in document re-organization?

### ISSUE THREAD

**Issue by tonyc** [sharkrf/openspot-http-api#3]
Hi there!

I've been doing some hacking with the API on my device, and I've found that specific info is hard to find -- mainly around the ordering and organization of the various API endpoints, and I have to scroll up and down a lot to find what I'm looking for.

I'm curious if you'd be open to a PR that reorganized this document a bit more logically, endpoints alphabetized within their section, and a list at the beginning of the document hyperlinked to each endpoint.

I currently have it organized into the following order, but would welcome other ideas to make info easier to find:

----

### User/Session Management
* `checkauth.cgi`
* `gettok.cgi`
* `login.cgi`
* `logout.cgi`

### Device Management
* `info.cgi`
* `ip.cgi` 
* `reboot.cgi`
* `status.cgi`

### Config Profile Management
* `config-export.cgi`
* `config-import.cgi`
* `cpsettings.cgi`

### Other Settings
* `locationsettings.cgi`
* `netsettings.cgi`
* `passwordsettings.cgi`
* `spksettings.cgi`

### Connector Management
* `connector.cgi`
* `connectorsettings.cgi`

### Connector Settings
* `c4fmautocal.cgi`
* `dcsxlxsettings.cgi`
* `dmrautocal.cgi`
* `dmrplussettings.cgi`
* `fcssettings.cgi`
* `homebrewsettings.cgi`
* `nullsettings.cgi`
* `refxrfsettings.cgi`
* `srfipconnclientsettings.cgi`
* `srfipconnserversettings.cgi`
* `status-srfipconnserver.cgi`
* `ysfrefsettings.cgi`

### Modem Management
* `modemcal.cgi`
* `modemcwid.cgi`
* `modemfreq.cgi`
* `modemmode.cgi`
* `modemmodulation.cgi`
* `modemother.cgi`
* `modempacket.cgi`
* `modemtdma.cgi`

### Mode/Network-specific Settings
* `bmmsettings.cgi`
* `c4fmsettings.cgi`
* `dmrsettings.cgi`
* `dstarsettings.cgi`
* `locksettings.cgi`
* `quickcall.cgi`
* `status-dmrsms.cgi`

**Comment by nonoo** [comment]
Yes, you can send the pull request, thank you!
